appConfig:
  theme: high-contrast-light
  layout: auto
  iconSize: small
  language: en
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 60
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
pageInfo:
  title: PTL Dashboard
  description: ''
  navLinks: []
  footerText: ''
sections:
  - name: Monitoring & Control
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Portainer
        icon: >-
          https://static-00.iconduck.com/assets.00/portainer-icon-366x512-rt9if7pd.png
        url: http://mahdy.th80:9111/#!/2/docker/containers
        target: modal
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:9111
        id: 0_1901_portainer
      - title: Twingate
        icon: >-
          https://global.discourse-cdn.com/standard17/uploads/twingate/original/1X/fb40be85d95830140c4cb51f7666dd4f50585d39.png
        url: https://hardshoft.twingate.com/
        target: newtab
        id: 1_1901_twingate
      - title: VPN
        description: >-
          We try to reach device swagger in prod. it is possible that vpn is up
          but this fails
        icon: >-
          https://play-lh.googleusercontent.com/MDDH7WLlwds0bkr-fLZKQ751gWGxbpuAtJGk5TRLFkHYr2rWM_hKHWHPhzVfgQ35YlhM
        url: ''
        statusCheck: true
        statusCheckUrl: https://device.teamusages.prod.protectline.fr/swagger-ui.html
        id: 2_1901_vpn
      - title: AWS apps
        icon: >-
          https://files.softicons.com/download/social-media-icons/free-social-media-icons-by-uiconstock/png/512x512/AWS-Icon.png
        url: https://protectline.awsapps.com/start/
        target: newtab
        id: 3_1901_awsapps
  - name: Dev
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Keycloak
        icon: >-
          https://cf.appdrag.com/dashboard-openvm-clo-b2d42c/uploads/Keycloak-VC4L-19JH.png
        url: http://mahdy.th80:7000
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:7000
        id: 0_287_keycloak
      - title: Consul
        icon: https://www.svgrepo.com/show/448216/consul.svg
        url: http://mahdy.th80:8590
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:8590
        id: 1_287_consul
      - title: Kafka
        icon: >-
          https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Apache_kafka-icon.svg/1200px-Apache_kafka-icon.svg.png
        url: http://mahdy.th80:7005
        target: newtab
        statusCheck: true
        statusCheckUrl: >-
          http://mahdy.th80:7005/api/docker-kafka-server/topic?search=&show=HIDE_INTERNAL&page=1
        id: 2_287_kafka
  - name: Remote env
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Webtop PTL
        icon: https://cdn-icons-png.flaticon.com/512/10321/10321987.png
        url: http://mahdy.th80:8200/
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:8200/
        id: 0_981_webtopptl
      - title: Code server
        icon: >-
          https://user-images.githubusercontent.com/5768801/99205104-8d519600-2785-11eb-9171-e2952f22d2ab.png
        url: https://mahdy.th80:7002
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:7002
        statusCheckAllowInsecure: true
        statusCheckAcceptCodes: '302'
        statusCheckMaxRedirects: '2'
        id: 1_981_codeserver
      - title: Firefox PTL
        icon: firefox_ptl.png
        url: http://mahdy.th80:5801
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:5801
        id: 2_981_firefoxptl
      - title: Firefox playground
        icon: >-
          https://static-00.iconduck.com/assets.00/firefox-icon-1981x2048-4izjijq3.png
        url: http://mahdy.th80:5800
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:5800
        id: 3_981_firefoxplayground
  - name: Swaggers - dev
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Device
        icon: >-
          https://static-00.iconduck.com/assets.00/swagger-icon-512x512-halz44im.png
        url: https://device.dev.protectline.fr/swagger-ui.html
        target: newtab
        statusCheck: true
        statusCheckUrl: https://device.dev.protectline.fr/swagger-ui.html
        id: 0_1263_device
      - title: Install
        icon: >-
          https://static-00.iconduck.com/assets.00/swagger-icon-512x512-halz44im.png
        url: >-
          https://installation.dev.protectline.fr/swagger-ui.html#/device-controller
        target: newtab
        statusCheck: true
        statusCheckUrl: >-
          https://installation.dev.protectline.fr/swagger-ui.html#/device-controller
        id: 1_1263_install
      - title: Event
        icon: >-
          https://static-00.iconduck.com/assets.00/swagger-icon-512x512-halz44im.png
        url: https://event.dev.protectline.fr/swagger-ui.html#/device-controller
        target: newtab
        statusCheck: true
        statusCheckUrl: https://event.dev.protectline.fr/swagger-ui.html#/device-controller
        id: 2_1263_event
      - title: DeviceManagement
        icon: >-
          https://static-00.iconduck.com/assets.00/swagger-icon-512x512-halz44im.png
        url: >-
          https://devicemanagement.dev.protectline.fr/swagger-ui.html#/device-controller
        target: newtab
        statusCheck: true
        statusCheckUrl: >-
          https://devicemanagement.dev.protectline.fr/swagger-ui.html#/device-controller
        color: '#5d34e3'
        id: 3_1263_devicemanagement
      - title: DM Orchestrator
        icon: >-
          https://static-00.iconduck.com/assets.00/swagger-icon-512x512-halz44im.png
        url: >-
          https://devicemanagement-orchestrator.dev.protectline.fr/swagger-ui.html
        target: newtab
        statusCheck: true
        statusCheckUrl: >-
          https://devicemanagement-orchestrator.dev.protectline.fr/swagger-ui.html
        color: '#5d34e3'
        id: 4_1263_dmorchestrator
  - name: Services - dev
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: DM FE
        icon: https://cdn-icons-png.flaticon.com/512/780/780457.png
        url: https://devicemanagement-fe.dev.protectline.fr/
        target: newtab
        statusCheck: true
        statusCheckUrl: https://devicemanagement-fe.dev.protectline.fr/
        id: 0_1264_dmfe
      - title: Keycloak
        icon: https://upload.wikimedia.org/wikipedia/commons/2/29/Keycloak_Logo.png
        url: https://keycloak-21.dev.protectline.fr/
        target: newtab
        statusCheck: true
        statusCheckUrl: https://keycloak-21.dev.protectline.fr/
        id: 1_1264_keycloak