appConfig:
  theme: high-contrast-light
  layout: auto
  iconSize: small
  language: en
  startingView: default
  defaultOpeningMethod: newtab
  statusCheck: false
  statusCheckInterval: 60
  faviconApi: allesedv
  routingMode: history
  enableMultiTasking: false
  widgetsAlwaysUseProxy: false
  webSearch:
    disableWebSearch: false
    searchEngine: duckduckgo
    openingMethod: newtab
    searchBangs: {}
  enableFontAwesome: true
  enableMaterialDesignIcons: false
  hideComponents:
    hideHeading: false
    hideNav: false
    hideSearch: false
    hideSettings: false
    hideFooter: false
  auth:
    enableGuestAccess: false
    users: []
    enableKeycloak: false
  showSplashScreen: false
  preventWriteToDisk: false
  preventLocalSave: false
  disableConfiguration: false
  disableConfigurationForNonAdmin: false
  allowConfigEdit: true
  enableServiceWorker: false
  disableContextMenu: false
  disableUpdateChecks: false
  disableSmartSort: false
  enableErrorReporting: false
pageInfo:
  title: Mahdy Dashboard
  description: ''
  footerText: ''
sections:
  - name: Monitoring & Control
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Portainer
        icon: >-
          https://static-00.iconduck.com/assets.00/portainer-icon-366x512-rt9if7pd.png
        url: http://mahdy.th80:9111/#!/2/docker/containers
        target: modal
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:9111
        id: 0_1901_portainer
      - title: Twingate
        icon: >-
          https://global.discourse-cdn.com/standard17/uploads/twingate/original/1X/fb40be85d95830140c4cb51f7666dd4f50585d39.png
        url: https://hardshoft.twingate.com/
        target: newtab
        id: 1_1901_twingate
      - title: PTL Dashy
        icon: https://dashy.to/img/dashy.png
        url: http://mahdy.th80:3001
        target: sametab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:3001
        id: 2_1901_ptldashy
  - name: Multimedia
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Photoprism
        icon: https://dl.photoprism.app/icons/bold.svg
        url: http://mahdy.th80:4200
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:4200
        id: 0_1035_photoprism
      - title: Jellyfin
        icon: >-
          https://techspot.com/images2/downloads/topdownload/2021/03/2021-03-22-ts3_thumbs-a00.png
        url: http://mahdy.th80:8182/
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:8182/
        id: 1_1035_jellyfin
      - title: Nextcloud
        icon: >-
          https://cdn.icon-icons.com/icons2/2699/PNG/512/nextcloud_logo_icon_168948.png
        url: http://mahdy.th80:4000
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:4000
        id: 2_1035_nextcloud
      - title: Wiki JS
        icon: >-
          https://cf.appdrag.com/dashboard-openvm-clo-b2d42c/uploads/wikijs-full-2021-768t-svg-yOi8.png
        url: http://mahdy.th80:3100
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:3100
        id: 3_1035_wikijs
      - title: Home
        icon: https://avatars.githubusercontent.com/u/12284211?s=280&v=4
        url: http://mahdy.th80:4100
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:4100
        statusCheckAcceptCodes: '401'
        id: 4_1035_home
      - title: src backup
        icon: https://avatars.githubusercontent.com/u/12284211?s=280&v=4
        url: http://mahdy.th80:4101
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:4101
        statusCheckAcceptCodes: '401'
        id: 5_1035_srcbackup
      - title: dest backup
        icon: https://avatars.githubusercontent.com/u/12284211?s=280&v=4
        url: http://mahdy.th80:4102
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:4102
        statusCheckAcceptCodes: '401'
        id: 6_1035_destbackup
  - name: Dev
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Keycloak
        icon: >-
          https://cf.appdrag.com/dashboard-openvm-clo-b2d42c/uploads/Keycloak-VC4L-19JH.png
        url: http://mahdy.th80:7000
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:7000
        id: 0_287_keycloak
      - title: Consul
        icon: https://www.svgrepo.com/show/448216/consul.svg
        url: http://mahdy.th80:8590
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:8590
        id: 1_287_consul
      - title: Kafka
        icon: >-
          https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Apache_kafka-icon.svg/1200px-Apache_kafka-icon.svg.png
        url: http://mahdy.th80:7005
        target: newtab
        statusCheck: true
        statusCheckUrl: >-
          http://mahdy.th80:7005/api/docker-kafka-server/topic?search=&show=HIDE_INTERNAL&page=1
        id: 2_287_kafka
  - name: Remote env
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Webtop PTL
        icon: https://cdn-icons-png.flaticon.com/512/10321/10321987.png
        url: http://mahdy.th80:5101
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:5101
        id: 0_981_webtopptl
      - title: Code server
        icon: >-
          https://user-images.githubusercontent.com/5768801/99205104-8d519600-2785-11eb-9171-e2952f22d2ab.png
        url: https://mahdy.th80:7002
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:7002
        statusCheckAllowInsecure: true
        statusCheckAcceptCodes: '302'
        statusCheckMaxRedirects: '2'
        id: 1_981_codeserver
      - title: Firefox PTL
        icon: firefox_ptl.png
        url: http://mahdy.th80:5001
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:5001
        id: 2_981_firefoxptl
      - title: Firefox playground
        icon: >-
          https://upload.wikimedia.org/wikipedia/commons/1/16/Firefox_logo%2C_2017.png
        url: http://mahdy.th80:5000
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:5000
        id: 3_981_firefoxplayground
      - title: Firefox Expensya
        icon: >-
          https://upload.wikimedia.org/wikipedia/commons/1/16/Firefox_logo%2C_2017.png
        url: http://mahdy.th80:5002
        target: newtab
        statusCheck: true
        statusCheckUrl: http://mahdy.th80:5002
        id: 4_981_firefoxexpensya